name: Go Build & Test
on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Set output
        id: vars
        run: echo ::set-output name=sha::${GITHUB_SHA}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Build & Test
        run: |
          go build -v .
          go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          APP_VERSION: ${{ steps.vars.outputs.sha }}
      - name: Verify version
        run: dist/release-drafter_linux_amd64/release-drafter version